apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo-app
spec:
  selector:
      app: todo-label
  type: NodePort
  ports:
      - port: 80
        targetPort: 8000
        nodePort: 32000


